### ISSUE TITLE
Allow external pull requests for fixed issues

### ISSUE THREAD

**Issue by Divide-By-0** [mafik/echo#20]
There are two repos with several changes, including:
https://github.com/infinity0/Circular-Recorder - this one allows to record to external storage instead of RAM, increasing the amount of time that can be recorded
https://github.com/jenisha010/echo - this one fixes the background recording problems and updates it to use the latest permissions. This resolves various issues like #14, #17.

However, it says only maintainers can make pull requests.

**Comment by mafik** [comment]
Big thanks. I didn't notice they're disabled. I've flipped some toggles and I think pull requests should be working now (I don't have a second account so can't really verify).

jenisha010's fork is a solid one, I'll pull that one right away!

**Comment by Go-rom** [comment]
Hello @mafik 
Would you be ok to provide a new release with these merged PR + Android 14+ compatibility please ?
Thank you

**Comment by mafik** [comment]
Hi @Go-rom !
I took a look at F-Droid documentation at  https://f-droid.org/docs/Update_Processing/. I understand that F-Droid servers build the APK according to metadata from this file: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/eu.mrogalski.saidit.yml. 

That metadata file seems like the right place to publish the new version but I'd need to test it out before sending a pull request. Unfortunately I can't do that. I've lost my Android setup some time ago. It seems that the F-Droid metadata file was edited by a bunch of folks over past years (https://gitlab.com/fdroid/fdroiddata/-/commits/master/metadata/eu.mrogalski.saidit.yml) so luckily it's not really blocked on me. I guess anybody can post an update to F-Droid if they would like to.

**Comment by mafik** [comment]
I'm not the right person to answer this question :/ Maybe somebody has some experience in F-Droid maintenance?

**Comment by Go-rom** [comment]
Hello @mafik 

Thank you for your answer, i'm sorry because i'm not able to help you out on this one, i'm not a dev so i've got no experience about this topic.
But please, allow me to summon the mighty @IzzySoft (Hi !) who surely might be able to enlight us on that matter.

**Comment by IzzySoft** [comment]
Auto-Updates are disabled there:

```yml
AutoUpdateMode: None
UpdateCheckMode: RepoManifest
CurrentVersion: 1.3.39
CurrentVersionCode: 14
```

Also the method `RepoManifest` is not really what's used anymore (tagged releases are the de-facto standard). But yeah, you could open an issue with their `fdroiddata` repo asking for assistance. Not much I can do; I cannot even offer you to list the app at IzzyOnDroid as you don't provide an APK file.

**Comment by jenisha010** [comment]
Hello @mafik If you don't have Android setup, I can send you the build APK or create a Release for test and send you a pull request. (I'm not sure if I create release on my forked repo and then raising a pull request will show up the release on original repo)

Publishing a newer version on F-Droid will help a lot of users to get their hands on the new version app. Let me know your thoughts.

**Comment by mafik** [comment]
Hi @jenisha010 ! Thanks for jumping in! I think the key is to update the manifest in the fdroiddata repository and check that it's still working. I have actually never submitted stuff to F-Droid so I don't have real experience in this stuff but F-Droid docs should have the instructions on doing that.

**Comment by Go-rom** [comment]
Thank you @IzzySoft for providing these advices.

@jenisha010 are you able to manage the `fdroiddata` repo update or do you need any help?

**Comment by Go-rom** [comment]
Hello everyone,

i'm reporting back some news : i decide to give it a try by setting up on a spare computer a F-droid building environment.

I did succeed to build the master branch but some questions remain.

1.  @mafik you need to increment `versionCode` to 15 and `versionName`  to 1.3.40 (or whatever the version you want) in `build.gradle`
2. @jenisha010 since your PR, i don't understand why `android:versionCode` and `android:versionName` have disappeared in `AndroidManifest.xml`. It's a real question, remember i'm not a dev but since these variables are present in the default template, i'm just wondering if it could cause any issue later.
3. The [F-Droid metadata file ](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/eu.mrogalski.saidit.yml) list all Echo's versions including 1.3.38 and 1.3.39. The problem is : if these old versions remain in the metadata file, the building process fails because they need Gradle 1.10.
And i don't know if when it comes to update the F-Droid repository, the older versions have to be built too.

Also i had to remove  ` - $$SDK$$/tools/bin/sdkmanager 'platforms;android-21' 'build-tools;21.0.2' > /dev/null` in order to make it work. Of course i tried to update versions (android-34, builds-tools;34.0.0)
The [dedicated documentation](https://developer.android.com/tools/sdkmanager) suggests to use double quotes instead of simple but it doesn't solve the issue.

Here's the kind of error i'm getting :

----

Allow me to also include the current rewritten metadata file.

<details>
<summary>Click to expand</summary>

```
Categories:
  - Multimedia
License: GPL-3.0-only
AuthorName: Marek Rogalski
AuthorEmail: mafikpl@gmail.com
AuthorWebSite: https://mrogalski.eu/
SourceCode: https://github.com/mafik/echo
IssueTracker: https://github.com/mafik/echo/issues

AutoName: Echo
Description: |-
  Continuously record audio for retrieval at a later time. Unless saved,
  recordings are deleted on a rolling basis.

  * record harassment and bullying (even when you didn't anticipated them)
  * save important pieces of information (phone numbers / passwords / instructions)
  * record cute/funny moments
  * prove that someone said (or didn't say) something

RepoType: git
Repo: https://github.com/Go-rom/echo

Builds:
  - versionName: 1.3.38
    versionCode: 13
    commit: 9dafc3895c6d40707b96be085e82df056160ca46
    subdir: SaidIt
    gradle:
      - yes
    srclibs:
      - jcaki@fc513da4f326ddfee45a2318b326c61ffa10838a
    rm:
      - SaidIt/libs/*
    prebuild:
      - sed -i -e 's/class/public class/g' $$jcaki$$/src/org/jcaki/Doubles.java
      - cp -fR $$jcaki$$/src/org src/main/java/
      - sed -i -e 's/v7:/v7:21./g' -e 's/v4:19/v4:21/g' -e 's/19.1.0/21.0.2/g' -e
        's/compileSdkVersion 19/compileSdkVersion 21/g' build.gradle

  - versionName: 1.3.39
    versionCode: 14
    commit: 79d591c086452a37494a6fd8976218a3773bdc05
    subdir: SaidIt
    gradle:
      - yes
    srclibs:
      - jcaki@fc513da4f326ddfee45a2318b326c61ffa10838a
    rm:
      - SaidIt/libs/*
      - legacy/1.0/libs/*
    prebuild:
      - sed -i -e 's/class/public class/g' $$jcaki$$/src/org/jcaki/Doubles.java
      - cp -fR $$jcaki$$/src/org src/main/java/
      - $$SDK$$/tools/bin/sdkmanager 'platforms;android-21' 'build-tools;21.0.2' >
        /dev/null

  - versionName: 1.3.40
    versionCode: 50
    commit: 4aa8ed2f6c8eda5f079ad35997fcd1c3f349692a
    subdir: SaidIt
    gradle:
      - yes
    srclibs:
      - jcaki@fc513da4f326ddfee45a2318b326c61ffa10838a
    rm:
      - SaidIt/libs/*
      - legacy/1.0/libs/*
    prebuild:
      - sed -i -e 's/class/public class/g' $$jcaki$$/src/org/jcaki/Doubles.java
      - cp -fR $$jcaki$$/src/org src/main/java/

AutoUpdateMode: None
UpdateCheckMode: RepoManifest
CurrentVersion: 1.3.40
CurrentVersionCode: 15
```
</details>

Note that for testing purposes, the metadata file targets the fork on my Github space.
If anyone is able to provide some answers, please jump in !
